import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RecoilProvider from "./recoilProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoilProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            {children}
            <Toaster
              position="top-center"
              toastOptions={{
                style:{
                background: "#1f2937", // Dark background
                color: "#ffffff", // White text
                border: "1px solid #4f46e5", // Add a border
                borderRadius: "8px", // Rounded corners
                padding: "16px", // Add padding
                }
              }}
              />
        </body>
        </RecoilProvider>
      </html>
  );
}
